<?php

declare(strict_types=1);

namespace Services\BoostersService;

use App\Models\Booster;
use App\Services\BoostersService\BoostersContract;
use App\Services\BoostersService\BoostersService;
use App\Services\BoostersService\BoostersTdo;
use Tests\TestCase;

final class BoostersServiceTest extends TestCase
{
    protected BoostersContract $service;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = new BoostersService();
    }

    public function test_add(): void
    {
        Booster::query()->delete();
        $item = new BoostersTdo(
            'unit test',
            'unit test',
            'unit test',
            'unit test',
        );
        $this->service->add($item);
        $total = Booster::query()->count();
        $this->assertEquals(1, $total);
        Booster::query()->delete();
    }
}
